name: BuycraftX
main: net.buycraft.plugin.bukkit.BuycraftPlugin
version: ${project.version}
author: Buycraft
commands:
  tebex:
    aliases: [ buycraft ]
    description: Main command for the Tebex plugin.